import Head from 'next/head'
import '../styles/globals.css'
import { Provider } from "react-redux";
import store from '../redux/index.jsx'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


function MyApp({ Component, pageProps }) {

  return (
    <Provider store={store}>
      <Head>
        <title>MyHandyAfrica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-secondary text-primary-900" style={{
        position: 'relative'
      }}>
        <Component {...pageProps} />
      </div>
      <ToastContainer />
    </Provider>
  )
}

export default MyApp
