import Head from 'next/head'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {

  return (<>
    <Head>
      <title>MyHandyAfrica</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="bg-secondary text-primary-900">
      <Component {...pageProps} />
    </div>
  </>)
}

export default MyApp
